# Generated by Django 2.2.2 on 2019-06-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.TextField(max_length=255, verbose_name='Nombre completo')),
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='C.C.')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contrasena')),
                ('telefono', models.TextField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.TextField(max_length=255, null=True, verbose_name='Direccion')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('rol', models.TextField(choices=[('TT', 'tutor'), ('EST', 'estudiante')], max_length=10)),
            ],
        ),
    ]
