# Generated by Django 2.2.2 on 2019-06-25 03:44

import AsesorateSAS_APP.validador
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsesorateSAS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.IntegerField()),
                ('horas', models.IntegerField(validators=[AsesorateSAS_APP.validador.validar_entero])),
                ('id_categoria', models.TextField(choices=[('JR', 'JUNIOR'), ('SB', 'SENIOR BASIC'), ('SM', 'SENIOR MEDIUM'), ('SA1', 'SENIOR ADVANCED 1'), ('SA2', 'SENIOR ADVANCED 2')])),
            ],
        ),
    ]
